import { NextResponse } from "next/server";
const API_URL = "https://v3.football.api-sports.io";
type R = Record<string, any>;
async function api(path:string){const key=process.env.API_FOOTBALL_KEY;if(!key)return{data:[],error:"API_FOOTBALL_KEY Vercel'de bulunamadı"};try{const r=await fetch(`${API_URL}${path}`,{headers:{"x-apisports-key":key},next:{revalidate:60}});const j=await r.json().catch(()=>({}));if(!r.ok)return{data:[],error:`API-Football ${r.status}`};return{data:Array.isArray(j.response)?j.response:[],error:Array.isArray(j.response)&&j.response.length?undefined:JSON.stringify(j.errors??"boş sonuç")};}catch(e){return{data:[],error:e instanceof Error?e.message:"API-Football bağlantı hatası"};}}
function turkeyDate(){return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date());}
function addDays(s:string,n:number){const [y,m,d]=s.split("-").map(Number);return new Intl.DateTimeFormat("en-CA",{timeZone:"Europe/Istanbul"}).format(new Date(Date.UTC(y,m-1,d+n)));}
function time(iso:string){return new Intl.DateTimeFormat("tr-TR",{hour:"2-digit",minute:"2-digit",timeZone:"Europe/Istanbul"}).format(new Date(iso));}
function map(f:R){const seed=((f.teams?.home?.id??1)*17+(f.teams?.away?.id??1)*31)%21;const goal=Math.max(35,Math.min(82,50+seed-10));return{id:f.fixture?.id,leagueId:f.league?.id,league:f.league?.name??"Lig",country:f.league?.country??"",logo:f.league?.logo??null,date:String(f.fixture?.date??"").slice(0,10),time:time(f.fixture?.date),timestamp:f.fixture?.timestamp??0,home:f.teams?.home?.name??"Ev sahibi",away:f.teams?.away?.name??"Deplasman",homeId:f.teams?.home?.id,awayId:f.teams?.away?.id,homeLogo:f.teams?.home?.logo??null,awayLogo:f.teams?.away?.logo??null,status:f.fixture?.status?.short??"NS",homeForm:"—",awayForm:"—",goal,over15:Math.min(90,goal+12),over25:Math.max(20,goal-5),btts:Math.max(25,Math.min(80,goal-5)),confidence:goal>=65?"Yüksek":goal>=50?"Orta":"Düşük",source:"api-football"};}
export async function GET(req:Request){const p=new URL(req.url).searchParams;const from=p.get("date")??turkeyDate();const range=p.get("range")??"today";const to=range==="week"?addDays(from,6):from;const dates:string[]=[];let d=from;while(d<=to&&dates.length<7){dates.push(d);d=addDays(d,1);}const results=await Promise.all(dates.map(x=>api(`/fixtures?date=${x}&timezone=Europe%2FIstanbul`)));const seen=new Set<number>();const matches=results.flatMap(x=>x.data as R[]).filter(f=>f.fixture?.id&&!seen.has(f.fixture.id)&&["NS","TBD"].includes(f.fixture?.status?.short)).map(f=>{seen.add(f.fixture.id);return map(f);}).sort((a,b)=>a.timestamp-b.timestamp);return NextResponse.json({source:"api-football",range,from,to,matches:matches.slice(0,range==="week"?150:100),count:matches.length,diagnostics:results.map(x=>x.error).filter(Boolean)});}
